### ISSUE TITLE
[Feat] Main Page

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/notion_based_blog_frontend#1]
## Describe the new feature<br/>
Make a main page. This page url will be `https://blog.yhs.kr/`

## TODO<br/>
- [ ] Design a main page
- [ ] Consider a main page
- [x] Make a Navbar Header
- [ ] Make a Component used by main page

## Addition Context<br/>
